### ISSUE TITLE
Lot of errors in HowTo 

### ISSUE THREAD

**Issue by senzacionale** [2020IP/TwentyTwenty.IdentityServer4.EntityFrameworkCore#18]
You have closed the issue but HowTo is still wrong :)

please add this to howto

``` javascript
services.AddEntityFrameworkSqlServer()
                .AddDbContext<ClientConfigurationContext>(o => o
                    .UseSqlServer(connectionString, b =>
                    b.MigrationsAssembly(typeof(Startup).GetTypeInfo().Assembly.GetName().Name)))
                .AddDbContext<ScopeConfigurationContext>(o => o
                    .UseSqlServer(connectionString, b =>
                    b.MigrationsAssembly(typeof(Startup).GetTypeInfo().Assembly.GetName().Name)))
                .AddDbContext<OperationalContext>(o => o
                    .UseSqlServer(connectionString, b =>
                    b.MigrationsAssembly(typeof(Startup).GetTypeInfo().Assembly.GetName().Name)));
```

and please fix this too, because ClientConfigurationContext constructor need to have TKey

``` javascript
public class ClientConfigurationContext : ClientConfigurationContext<Guid>
    {
        public ClientConfigurationContext(DbContextOptions<ClientConfigurationContext> options)
            : base(options)
        { }
    }
```

So if I add connectionString to my DB then everything should work out of the box?

Do I also need to add reference for both Microsoft.EntityFrameworkCore and Microsoft.EntityFrameworkCore.SqlServer?

Currently I get:

``` javascript
System.InvalidOperationException
Unable to resolve service for type 'Microsoft.EntityFrameworkCore.DbContextOptions`1[TwentyTwenty.IdentityServer4.EntityFrameworkCore.DbContexts.ClientConfigurationContext`1[System.Guid]]' while attempting to activate 'Host.Web.Configuration.ClientConfigurationContext'.
```

**Comment by ericgreenmix** [comment]
Fixing documentation is a great way to get open source contributions. In the future you might want to consider submitting a PR with the syntax fixes.

The `ClientConfigurationContext` does not need to have `TKey` in the constructor. It should work as shown. It looks like the error you are getting is because you have the `Guid/TKey` in the constructor with it.

You will need to setup the project just like you do any other EFCore project by adding the appropriate packages, which include `Microsoft.EntityFrameworkCore` and the appropriate database package. I.E. `Microsoft.EntityFrameworkCore.SqlServer` if you are using SqlServer.

**Comment by senzacionale** [comment]
In my opinion should be like so, other way does not compile:

```
public class ClientConfigurationContext : ClientConfigurationContext<Guid>
    {
        public ClientConfigurationContext(DbContextOptions<ClientConfigurationContext<Guid>> options)
            : base(options)
        { }
    }
```

I can submit of course and help

**Comment by senzacionale** [comment]
I will close the issue now
